### ISSUE TITLE
Make examples dir (with examples!)

### ISSUE THREAD

**Issue by bocajnotnef** [mercere99/Empirical#13]
For easy demoing/explanations, etc.

Perhaps steal from UTests...?

**Comment by mercere99** [comment]
Examples from UTests/web/ are actually already just example files (not real tests), so this makes a lot more sense than what we have right now.

**Comment by bocajnotnef** [comment]
Excellent. I'll work on migrating these.

**Comment by bocajnotnef** [comment]
- [ ] Make examples dir
 - [ ] Migrate utests/web

**Comment by bocajnotnef** [comment]
- [ ] Document examples...?

**Comment by bocajnotnef** [comment]
I'm realizing that I probably won't be the best candidate to document the examples, so I'll leave that to @mercere99. 

The rest will be resolved in #23

**Comment by bocajnotnef** [comment]
Closing #13, solved by #23

**Comment by bocajnotnef** [comment]
Welp. I moved everything, though there's nothing really telling people how to use the examples.

Oh well.

Closing #13, solved by #23
