### ISSUE TITLE
Repo License

### ISSUE THREAD

**Issue by bocajnotnef** [mercere99/Empirical#14]
So we've just about settled on implementing an MIT license for Empirical. 

One thing of note is that Doxygen uses a GPL license, though it looks like MIT will interface with that nicely.

**Comment by mercere99** [comment]
According to the Doxygen license: Documents produced by doxygen are derivative works derived from the input used in their production; they are not affected by this license.

So, we should be just fine using it.

**Comment by bocajnotnef** [comment]
Excellent!

**Comment by bocajnotnef** [comment]
Closing #14, fixed by #15
