### ISSUE TITLE
Make diff-cover maketarget

### ISSUE THREAD

**Issue by bocajnotnef** [mercere99/Empirical#18]
Make target that'll complain at the user if they write code that isn't covered by the tests

**Comment by bocajnotnef** [comment]
Also, important note here (and also why test coverage probably looks better than it is): gcov, for some silly reason, doesn't give any info on files that aren't covered at all by tests.

That is, if a file doesn't have code executed by a test it doesn't show up in our metrics. So there's a ton of files that currently have *no* coverage that *don't* affect our stats.

Pretty sure there's utilities to handle this--found an issue on the gcov tracker where someone complained about this and the dev team was like "Yeah, that's expected behaviour," so I don't think there's a fix within gcov. 

Things to look at: https://cobertura.github.io/cobertura/

Cobertura is for java projects though, so possibly not, but I know they do handle procesisng of coverage info and they integrate with Jenkins, so there should be other CI soulutions

**Comment by mercere99** [comment]
This all makes sense.  You may always have files that aren't really part of a project and you don't want to be affected by tests.  I'm fine with making sure we have some coverage on each file when we want it to.
But yes, we should be careful with it.

**Comment by bocajnotnef** [comment]
After a quick skim it looks like imlementing gcovr + gcov instead of lcov + gcov will do what we need--or at least provide an easier way to interface with other test coverage tracking freamewoks, e.g. cobertura

http://gcovr.com/guide.html

**Comment by bocajnotnef** [comment]
Difficulty: looks like Cobertura integrates with *jenkins* and not Travis.

I'd vastly prefer something that integrates with Travis (jenkins is a royal pain).

Regardless, gcovr might be useful, as it spews out xml.

**Comment by bocajnotnef** [comment]
(Objective: Have a way to metric changes in code coverage over time)

**Comment by bocajnotnef** [comment]
closing #18, fixed in #25
