### ISSUE TITLE
Documentation to Add

### ISSUE THREAD

**Issue by bocajnotnef** [mercere99/Empirical#3]
Obviously there's a lot, but now we can keep track of it. I'll add to this as I find stuff.

These should probably all be their own separate issues, but eh.

 - [x] License ( suggested: the MIT license http://choosealicense.com/licenses/mit/ )
 - [ ] Preferred formatting tools (potentially include automated checking for formatting; "Writing tools to enforce policy", etc)

**Comment by emilydolson** [comment]
My two cents on licenses: since the goal of this project is for other people to use it, it should have a license (otherwise people won't know whether it's okay for them to use and build on it). http://choosealicense.com is a good resource.

**Comment by bocajnotnef** [comment]
I'm also not sure what MSU's requirements are for licensing (or even if this project falls under their purview)

**Comment by mercere99** [comment]
I had planned on MIT license (and that's what I told github when I setup the repository), but never followed up to put one in place.  Good call.

**Comment by emilydolson** [comment]
Sounds good! I feel like it's hard to go wrong with the MIT license.

**Comment by bocajnotnef** [comment]
Alright, I'll put one together.

**Comment by mercere99** [comment]
Regarding preferred formatting, I do have a page on the wiki about this:
https://github.com/mercere99/Empirical/wiki/Coding-Guidelines

I'm happy to consider changes.   I have not looked into formatting tools, but agree that this could be a valuable step.  My biggest concern is that the tools might be thrown by the mix of C++ and JavaScript.

**Comment by bocajnotnef** [comment]
Closing #3, fixed by #15 and... something else, I'm sure.

**Comment by bocajnotnef** [comment]
Actually closing #3 this time
