### ISSUE TITLE
Some calls to emp_assert() are broken

### ISSUE THREAD

**Issue by emilydolson** [mercere99/Empirical#4]
Looks like commit https://github.com/mercere99/Empirical/commit/8f69dd68b13c38ad714a5db83ef7d1935a9d87d5 made it necessary to add an extra set of parentheses inside a lot of (maybe all?) emp_assert() calls. As a result, some stuff in JSWrap.h, vector.h, and functions.h broke (and maybe elsewhere as where). I added the necessary parentheses in those three files to get my code to compile, but haven't pushed those changes yet because I don't know if there's an easy fix to emp_assert() so it doesn't require the extra parentheses.

**Comment by mercere99** [comment]
Sorry about that -- it's fixed now.  I had run all the basic tests, but this was an interaction between emp_assert and Emscripten.  I had streamlined some of the macro assembly tools, but failed to fix how the Emscripten version of emp_assert was using them.
