### ISSUE TITLE
Documentation engine?

### ISSUE THREAD

**Issue by bocajnotnef** [mercere99/Empirical#5]
So there's essentially two paths we could take for having docs. We could have plain text docs or we could have docs managed by an engine e.g. Sphinx (http://sphinx-doc.org/contents.html).

Pros to flat: No dependency hell

Pros to engine'd: Prettier, usually more navigable, easily structured

+1 to engine'd and to Sphinx specifically, but that's just because I know it. Thoughts/comments?

**Comment by emilydolson** [comment]
I am definitely in favor of not reinventing the wheel, and have been meaning to learn Sphinx. It can handle unit tests to some extent too, right? How would this interact with something like a github wiki?

**Comment by ruppmatt** [comment]
I strongly recommend Sphinx.  But do heed it's limits: last I knew there
were problems with documenting certain types of templates.

On Sun, Oct 4, 2015 at 9:41 PM, Jake Fenton <notifications@github.com>
wrote:

> So there's essentially two paths we could take for having docs. We could
> have plain text docs or we could have docs managed by an engine e.g. Sphinx
> (http://sphinx-doc.org/contents.html).
>
> Pros to flat: No dependency hell
>
> Pros to engine'd: Prettier, usually more navigable, easily structured
>
> +1 to engine'd and to Sphinx specifically, but that's just because I know
> it. Thoughts/comments?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mercere99/Empirical/issues/5>.
>



-- 
Dr. Matthew Rupp
Post-Doctoral Research Associate
BEACON Center for the Study of Evolution in Action
An NSF Science and Technology Center
Michigan State University

**Comment by bocajnotnef** [comment]
Actually that's a good point, I don't know how Sphinx will interact within a c++ project.

**Comment by bocajnotnef** [comment]
I should point out there's also Doxygen, which is rather popular, though I have mixed feelings about how usable it is.

**Comment by bocajnotnef** [comment]
Looks like mentioning doxygen was somewhat silly on my part since Sphynx uses Doxygen to extract the relevant information to build the docs. It also requires an extension to do so--Breathe: https://breathe.readthedocs.org/en/latest/

Assuming nobody has any objections to this I can start working on integrating it.

**Comment by mercere99** [comment]
I quite like Sphinx from a user perspective, but I haven't tried working with it year.  The Emscripten documentation is all generated with it:
http://kripken.github.io/emscripten-site/
...which I take as the biggest endorsement.

**Comment by bocajnotnef** [comment]
Closing #5, fixed by #10
