### ISSUE TITLE
Document PR/git cleanup

### ISSUE THREAD

**Issue by bocajnotnef** [mercere99/Empirical#8]
From https://github.com/dib-lab/khmer/issues/1013

Used to quickly squash commits pre-merge

**Comment by mercere99** [comment]
This looks like a fantastic set of instructions.  My one question: does this lose all of the commit logs?  At some point do you need to manually re-enter them?

**Comment by mercere99** [comment]
Actually, I'm just remember that khmer keeps a changelog or somesuch rather than making an entry for each commit.  That would make the problem I mention above go away.

**Comment by bocajnotnef** [comment]
They don't keep a log for each commit but for each contribution to master,
which I think works rather well.

Squashing does destroy git history though, which is something of an issue.
It was impelled largely to keep large amounts of commits in working
branches from making it difficult to sort through the history of the master
branch.

**Comment by bocajnotnef** [comment]
Closing #8 as it was decided that squashing commits is a largely cosmetic thing with no real benefits at this point in the project lifecycle.
